{
 "title": "Kubernetes Nodes",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "instance",
    "query": "label_values(node_boot_time_seconds{app=\"node-exporter\"},  instance)"
   }
  ]
 },
 "panels": [
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Utilisation",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - avg by (instance) (irate(node_cpu_seconds_total{instance=\"$instance\", mode=\"idle\"}[5m]))",
     "legendFormat": "Utilisation"
    }
   ]
  },
  {
   "title": "CPU Saturation",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{instance=\"$instance\"}",
     "legendFormat": "Saturation (1m)"
    },
    {
     "expr": "node_load5{instance=\"$instance\"}",
     "legendFormat": "Saturation (5m)"
    },
    {
     "expr": "node_load15{instance=\"$instance\"}",
     "legendFormat": "Saturation (15m)"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Memory Utilisation",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(node_memory_Cached_bytes{instance=\"$instance\"} \n  + \n node_memory_Buffers_bytes{instance=\"$instance\"}\n  + \n node_memory_MemFree_bytes{instance=\"$instance\"}) \n/\n(node_memory_MemTotal_bytes)",
     "legendFormat": "Utilisation"
    }
   ]
  }
 ]
}